/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    UniCard: typeof import('@dcloudio/uni-ui/lib/uni-card/uni-card.vue')['default']
    UniSegmentedControl: typeof import('@dcloudio/uni-ui/lib/uni-segmented-control/uni-segmented-control.vue')['default']
  }
}
