import { defineUniPages } from '@uni-helper/vite-plugin-uni-pages'

export default defineUniPages({
  pages: [],
  globalStyle: {
    backgroundColor: '@bgColor',
    backgroundColorBottom: '@bgColorBottom',
    backgroundColorTop: '@bgColorTop',
    backgroundTextStyle: '@bgTxtStyle',
    navigationBarBackgroundColor: '#000000',
    navigationBarTextStyle: '@navTxtStyle',
    navigationBarTitleText: 'Uni Creator',
    navigationStyle: 'custom',
  },
  subPackages: [],
  tabBar: {
    custom: false,
    customize: false,
    overlay: true,
    height: '4rem',
    color: '@tabColor',
    selectedColor: '@tabSelectedColor',
    backgroundColor: '@tabBgColor',
    borderStyle: '@tabBorderStyle',
    list: [
      // GENERATED BY UNI-PAGES, PLATFORM: APP || H5 || MP-WEIXIN
      {
        pagePath: 'pages/index',
        text: '主页',
        selectedIconPath: 'static/tabbar/home-a.png',
        iconPath: 'static/tabbar/home.png',
      },
      {
        pagePath: 'pages/tasks',
        text: '任务',
        selectedIconPath: 'static/tabbar/tasks-a.png',
        iconPath: 'static/tabbar/tasks.png',
      },
      {
        pagePath: 'pages/user',
        text: '我的',
        selectedIconPath: 'static/tabbar/user-a.png',
        iconPath: 'static/tabbar/user.png',
      },
    ],
  },
})
